name: prueba aut
on:
  workflow_dispatch:
    inputs:
      version:
        description: Número de versión para el pre-release a crear. Ejemplo 1.1.3. | En caso de hotfix especificar la rama fix/. Ejemplo. fix/3.0.1
        required: true
        type: string
      dynamodb:
        description: 'Desmarcar la casilla para desactivar la insercion a DynamoDB'
        required: false
        default: true
        type: boolean

jobs:
  prueba:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v2

    - name: Revisión manual
      run: echo "Por favor, revisa y aprueba la Pull Request. Después, puedes ejecutar el flujo de trabajo."

    - name: Ejecutar prueba
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.version && github.event.inputs.dynamodb
      run: echo "prueba de GitHub Action"