name: Flujo de Trabajo Principal

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v2

      # Aquí van tus pasos de construcción, prueba, etc.

  approve:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Aprobar
        id: approve
        run: echo "Se requiere aprobación manual"
      - name: Establecer aprobación
        run: echo "::set-output name=approved::true"

  deploy:
    runs-on: ubuntu-latest
    needs: approve
    if: needs.approve.outputs.approved == 'true'
    steps:
      - name: Despliegue
        run: echo "Despliegue del código a producción"