name: Prueba de GitHub Action

on:
  push:
    branches:
      - main

jobs:
  prueba:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v2

    - name: Ejecutar prueba
      run: echo "prueba de GitHub Action"